<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

1. Compute the scaler product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number. 

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [1]:
import numpy as np

In [9]:
a = [-12, 16]
b = [12, 9]
(a[0]*b[0]) + (a[1]*b[1])

0

In [10]:
np.dot(a,b)

0

2. Compute the cross product of two vectors

> When a and b start at the origin point (0,0,0), the Cross Product will end at:

        cx = aybz − azby
        cy = azbx − axbz
        cz = axby − aybx
        
Hint: [Cross Product](https://www.mathsisfun.com/algebra/vectors-cross-product.html)

In [4]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])

In [5]:
[[x[0][1]*y[0][2] - x[0][2]*y[0][1],x[0][2]*y[0][0] - x[0][0]*y[0][2], x[0][0]*y[0][1] - x[0][1]*y[0][0]],
[x[1][1]*y[1][2] - x[1][2]*y[1][1],x[1][2]*y[1][0] - x[1][0]*y[1][2], x[1][0]*y[1][1] - x[1][1]*y[1][0]]]

[[-3, 6, -3], [3, -6, 3]]

In [6]:
np.cross(x,y)

array([[-3,  6, -3],
       [ 3, -6,  3]])

3. Compute the Hademard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [11]:
a1 = np.array([[1,2],[3,4]])
b1 = np.array([[5,6],[7,8]])

In [13]:
[[a1[0][0]*b1[0][0],a1[0][1]*b1[0][1]],[a1[1][0]*b1[1][0],a1[1][1]*b1[1][1]]]

[[5, 12], [21, 32]]

In [12]:
np.multiply(a1,b1)

array([[ 5, 12],
       [21, 32]])

4. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [16]:
# Program to add two matrices using nested loop

X1 = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y1 = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

In [32]:
def addtwomatrices(mat1,mat2):
    for a in range(len(mat1)):
        for b in range(len(mat2[0])):
            result[a][b] = mat1[a][b] + mat2[a][b]
            return result

In [33]:
addtwomatrices(X1,Y1)

[[17, 15, 4], [10, 12, 9], [11, 13, 18]]

5. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [68]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X2 = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y2 = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result2 = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

In [69]:
def addtwodiffmatrices(mat1,mat2):
    for a in range(len(mat1)):
        for b in range(len(mat2[0])):
            for c in range(len(mat2)):
                result2[a][b] += mat1[a][c] * mat2[c][b]
    for i in result2:
        print(i)

In [70]:
addtwodiffmatrices(X2,Y2)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [45]:
np.matmul(X2,Y2)

array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

6. Compute the determinant of an n x n matrix.

![](https://integratedmlai.com/wp-content/uploads/2018/12/Matrix_Det_2x2.png)

Hint: [Find the Determinant of a Matrix with Pure Python without Numpy or Scipy](https://integratedmlai.com/find-the-determinant-of-a-matrix-with-pure-python-without-numpy-or-scipy/)

Hint: Use 
> np.linalg.det

In [71]:
help(np.linalg.det)

Help on function det in module numpy.linalg:

det(a)
    Compute the determinant of an array.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Input array to compute determinants for.
    
    Returns
    -------
    det : (...) array_like
        Determinant of `a`.
    
    See Also
    --------
    slogdet : Another way to represent the determinant, more suitable
      for large matrices where underflow/overflow may occur.
    scipy.linalg.det : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    The determinant is computed via LU factorization using the LAPACK
    routine ``z/dgetrf``.
    
    Examples
    --------
    The determinant of a 2-D array [[a, b], [c, d]] is ad - bc:
    
    >>> a = np.array([[1, 2], [3, 4]])
    >>> np.linalg.det(a)
    -2.0 # may vary
    
    Computing determinants for a stack of matrices:
    
 

In [72]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]

In [73]:
np.linalg.det(matrix)

17.999999999999996

7. Compute the inverse of an n x n matrix.

For a 3×3 matrix

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation3.gif)

the matrix inverse is

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation4.gif)

Hint: Use 
> from numpy.linalg import inv

In [75]:
a_array = np.array([[1., 2.], [3., 4.]])

In [77]:
from numpy.linalg import inv
np.linalg.inv(a_array)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])



---



---



> > > > > > > > > © 2021 Institute of Data


---



---



